name: Generate Baseline Profiles

on:
  push:
    branches: [ main, tm/bp-generator-automation ]
  workflow_dispatch:

jobs:
  # This job checks for any file changed within MacrobenchmarkSample/ folder 
  # to distinguish if the build check for Macrobenchmark is needed to be run.
  # It sets the outputs.macrobenchmark to true/false based on the changes.
  # In the next build job, it checks for needs.changes.outputs.macrobenchmark == 'true' 
  # or skips the job otherwise.
#  changes:
#    if: github.repository_owner == 'android'
#    runs-on: macos-latest
#    # Set job outputs to values from filter step to be able to use it in next job
#    outputs:
#      macrobenchmark: ${{ steps.filter.outputs.macrobenchmark }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 1
#      - uses: dorny/paths-filter@v2
#        id: filter
#        with:
#          filters: |
#            macrobenchmark:
#              - 'MacrobenchmarkSample/**'

  baseline-profile:
#    needs: changes
#    # Only run action for the main repo & not forks and if change is in macrobenchmark sample
#    if: github.repository_owner == 'android' && needs.changes.outputs.macrobenchmark == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        id: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Run Generator with GMD
        run: >
          ./gradlew :macrobenchmark:pixel6Api31BenchmarkAndroidTest 
          -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
          -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile

#      - name: Build Macrobenchmark Sample
#        uses: eskatos/gradle-command-action@v1
#        env:
#          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
#        with:
#          arguments: build
#          build-root-directory: ${{ github.workspace }}/MacrobenchmarkSample
#          gradle-executable: ${{ github.workspace }}/MacrobenchmarkSample/gradlew
#          wrapper-directory: ${{ github.workspace }}/MacrobenchmarkSample/gradle/wrapper
